// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  入力デバイスを挙げる。 */
	listDevices: () => typedError<DeviceView[], AppError>(__TAURI_INVOKE("list_devices")),
	/**  ライブラリの中身を挙げる。 */
	listProjects: () => typedError<ProjectView[], AppError>(__TAURI_INVOKE("list_projects")),
	/**  プロジェクトを作る。 */
	createProject: (displayName: string) => typedError<string, AppError>(__TAURI_INVOKE("create_project", { displayName })),
	/**  プロジェクトを開く。 */
	openProject: (id: string) => typedError<ProgressView, AppError>(__TAURI_INVOKE("open_project", { id })),
	/**  いまの進み具合。 */
	progress: () => typedError<ProgressView, AppError>(__TAURI_INVOKE("progress")),
	/**
	 *  デバイスを選び、ストリームを開く。
	 * 
	 *  返るのは、OS 側の音声加工が残っているかどうか（`TR-REC-11`）。
	 */
	armDevice: (deviceId: string) => typedError<MicModeView, AppError>(__TAURI_INVOKE("arm_device", { deviceId })),
	/**
	 *  入力が届いているかを確かめる（`TR-REC-17`）。
	 * 
	 *  権限が無いと macOS は無音を返す。 成否ではなくピークを見る。
	 */
	probeInput: (ms: number) => typedError<Finite, AppError>(__TAURI_INVOKE("probe_input", { ms })),
	/**  いま録るべき行の収録を始める。 */
	startTake: () => typedError<string, AppError>(__TAURI_INVOKE("start_take")),
	/**
	 *  行を指定して録り直す（`TR-REC-21`, `TR-RCL-25`, `TR-ALN-27`）。
	 * 
	 *  既存のテイクを消さない。 世代を1つ足して積み、採用を新しい方へ切り替える。
	 */
	startRetake: (rowId: string) => typedError<string, AppError>(__TAURI_INVOKE("start_retake", { rowId })),
	/**  全部の行と、そのテイク（`TR-REC-21`, `TR-RCL-25`）。 */
	rowsWithTakes: () => typedError<RowTakesView[], AppError>(__TAURI_INVOKE("rows_with_takes")),
	/**
	 *  採用テイクを切り替える（`TR-RCL-25`）。
	 * 
	 *  カバレッジは変わらない。 変わるのは原音設定の値だけ。
	 */
	adoptTake: (rowId: string, takeId: number) => typedError<null, AppError>(__TAURI_INVOKE("adopt_take", { rowId, takeId })),
	/**  そのテイクの原音設定を、エイリアスごとに引く（`TR-ALN-33`）。 */
	otosOfTake: (takeId: number) => typedError<OtoView[], AppError>(__TAURI_INVOKE("otos_of_take", { takeId })),
	/**
	 *  録れたものをそのまま鳴らす（`TR-REC-43`）。合成を通さない。
	 * 
	 *  返すのは長さ（ミリ秒）。
	 */
	playTake: (takeId: number) => typedError<Finite, AppError>(__TAURI_INVOKE("play_take", { takeId })),
	/**
	 *  いま入ってきている音の包絡を送り続ける（`TR-REC-43`）。
	 * 
	 *  `invoke` で引かせず Channel で送る理由は `DEC-PLT-017`。
	 * 
	 *  この関数が固有に守っているのは2つ。`studio` のロックを取らないので、
	 *  テイクの確定（アライメントを含む）のあいだも波形が止まらない。
	 *  進んでいないフレームは送らないので、同じ絵を描き直させない。
	 */
	streamEnvelope: (onFrame: Channel<EnvelopeView>) => __TAURI_INVOKE<number>("stream_envelope", { onFrame }),
	/**
	 *  波形を送るのをやめる（`TR-REC-43`）。
	 * 
	 *  止める相手を名指しする。 ただ世代を進めるだけにすると、
	 *  画面が作り直されたときに新しい流れを殺してしまう——
	 *  「古いのを止める」と「新しいのを始める」は非同期に飛ぶので、
	 *  後者が先に着くことがある。そのときに数を進めると、生きているほうが止まる。
	 */
	stopEnvelopeStream: (generation: number) => __TAURI_INVOKE<void>("stop_envelope_stream", { generation }),
	/**  収録を止めて、テイクを確定させる。 */
	finishTake: () => typedError<TakeView, AppError>(__TAURI_INVOKE("finish_take")),
	/**  収録済みのテイクを、指定した音高で鳴らす。 */
	preview: (takeId: number, midi: number, lengthMs: Finite) => typedError<number, AppError>(__TAURI_INVOKE("preview", { takeId, midi, lengthMs })),
	/**  プリロールがどれだけ溜まっているか（ミリ秒、`TR-REC-19`）。 */
	prerollMs: () => typedError<number, AppError>(__TAURI_INVOKE("preroll_ms")),
	/**  残量を見積もる（`TR-REC-41`）。 */
	estimateSpace: () => typedError<SpaceView, AppError>(__TAURI_INVOKE("estimate_space")),
	/**
	 *  入力レベルを校正する（`TR-REC-14`）。
	 * 
	 *  関門にしない。 収束しなくても収録に進める。
	 */
	calibrate: (seconds: Finite) => typedError<CalibrationView, AppError>(__TAURI_INVOKE("calibrate", { seconds })),
	/**
	 *  保存してある校正と、いまのゲインの差（`TR-REC-15`）。
	 * 
	 *  勝手に戻さない。 差があることを返すだけ。
	 */
	gainDrift: () => typedError<[Finite, Finite] | null, AppError>(__TAURI_INVOKE("gain_drift")),
	/**  保存してあるゲインへ戻す（`TR-REC-15`）。本人が選んだときだけ呼ぶ。 */
	restoreSavedGain: () => typedError<null, AppError>(__TAURI_INVOKE("restore_saved_gain")),
	/**
	 *  次のフレーズへ進むまでの長さ（ミリ秒、`TR-REC-20`）。
	 * 
	 *  単独音はガイドを使わないので固定長。 発話の検出結果を条件にしない。
	 */
	autoAdvanceMs: () => __TAURI_INVOKE<Finite>("auto_advance_ms"),
	/**
	 *  出力がどこへ出ているらしいか（`TR-REC-24`）。
	 * 
	 *  一次の足切りでしかない。 ドライバの自己申告なので、
	 *  実際の回り込みは [`check_guide_leak`] が録った音で確かめる。
	 */
	outputKind: () => typedError<OutputKindView, AppError>(__TAURI_INVOKE("output_kind")),
	/**
	 *  ガイドを鳴らしながら録って、回り込みを確かめる（`TR-REC-24`）。
	 * 
	 *  これを置かないと、全テイクにガイドが混入した音源が完成に到達しうる。
	 */
	checkGuideLeak: (midi: number) => typedError<LeakView, AppError>(__TAURI_INVOKE("check_guide_leak", { midi })),
	/**
	 *  音高を鳴らす（`TR-REC-23` の音高提示）。
	 * 
	 *  回り込みが確かめられていなければ鳴らさない。
	 */
	playPitch: (midi: number) => typedError<null, AppError>(__TAURI_INVOKE("play_pitch", { midi })),
	/**  曲ごとの状態を、手が届く順に返す（`TR-RCL-17`）。 */
	songStatus: () => typedError<SongView[], AppError>(__TAURI_INVOKE("song_status")),
	/**  UST を取り込む（`TR-RCL-12`）。主経路はこれ。 */
	importUst: (bytes: number[], title: string) => typedError<string, AppError>(__TAURI_INVOKE("import_ust", { bytes, title })),
	/**  曲をバンクから外す／戻す（`TR-RCL-12`）。曲そのものは消さない。 */
	setSongInBank: (id: string, inBank: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_song_in_bank", { id, inBank })),
	/**
	 *  曲を歌わせる（`TR-SYN-01`〜`04`, `TR-SYN-18`）。
	 * 
	 *  先頭フレーズができた時点で鳴りはじめる。 曲全体の合成を待たない。
	 */
	singSong: (id: string) => typedError<SungSongView, AppError>(__TAURI_INVOKE("sing_song", { id })),
	/**
	 *  背後で待っている仕事の数（`TR-SYN-33`, `TR-SYN-34`）。
	 * 
	 *  「録音終了 → 試唱ボタン活性化」の間に、無言の待ち時間を作らない。
	 *  画面はこれを見て、進んでいることを出す。
	 */
	pendingWork: () => typedError<number, AppError>(__TAURI_INVOKE("pending_work")),
	/**  試唱の待ち時間を返す（`TR-SYN-33`）。 */
	latencyReport: () => typedError<LatencyView[], AppError>(__TAURI_INVOKE("latency_report")),
	/**
	 *  見えている範囲の波形（`TR-PLT-04`）。
	 * 
	 *  上下の組を画素数ぶん返す。 読む量は画素数に比例し、範囲の広さには比例しない。
	 */
	waveformWindow: (takeId: number, fromMs: Finite, toMs: Finite, pixels: number) => typedError<([Finite, Finite])[], AppError>(__TAURI_INVOKE("waveform_window", { takeId, fromMs, toMs, pixels })),
	/**
	 *  見えている範囲のスペクトログラムを作る（`TR-PLT-04`）。
	 * 
	 *  素材ファイル全体を先に計算しない。
	 */
	spectrogramWindow: (takeId: number, fromMs: Finite, toMs: Finite, columns: number, rows: number) => typedError<SpectrogramView, AppError>(__TAURI_INVOKE("spectrogram_window", { takeId, fromMs, toMs, columns, rows })),
	/**  書き出す前の関門（`TR-REC-16`, `TR-REC-32`）。 */
	preflight: () => typedError<PreflightView, AppError>(__TAURI_INVOKE("preflight")),
	/**
	 *  全チャンネルを混ぜる（`TR-REC-06`）。
	 * 
	 *  全チャンネルに有意な信号があるときだけ選べる。
	 */
	useMixedChannels: () => typedError<null, AppError>(__TAURI_INVOKE("use_mixed_channels")),
	/**  鳴らしている音を止める。 */
	stopPreview: () => typedError<null, AppError>(__TAURI_INVOKE("stop_preview")),
};

/* Types */
/**  画面へ返す失敗。 */
export type AppError = {
	/**  送信してよい種別文字列。 */
	kind: string,
	/**  画面に出す説明。送信層へ載せない。 */
	message: string,
};

/**  画面へ返す校正の結果（`TR-REC-14`）。 */
export type CalibrationView = {
	/**  決めたゲイン（0.0〜1.0）。触れなければ `null`。 */
	gain: number | null,
	/**
	 *  `hardware` / `software` / `unavailable`。
	 * 
	 *  `hardware` 以外では自動調整しない（`TR-REC-14`）。
	 *  画面は OS 設定での調整を1回だけ案内する。
	 */
	control: GainControlView,
	/**  最後に測ったピーク（dBFS）。無音は `null`。 */
	peak_dbfs: number | null,
	/**  目標範囲（-12〜-6 dBFS）に入ったか。入らなくても収録には進める。 */
	settled: boolean,
};

/**  画面へ返すデバイス。 */
export type DeviceView = {
	/**  永続識別子（`TR-REC-03`）。同一性の判定はこれで行う。 */
	id: string,
	/**  表示名。一覧に出すためだけ。 */
	name: string,
};

/**  画面へ返す、いま流れている音の包絡（`TR-REC-43`）。 */
export type EnvelopeView = {
	/**
	 *  目盛りごとの min/max。畳まずにそのまま渡す。
	 * 
	 *  割り切れない本数へ畳むと絵が揺れる。 画面は1本につき1列を描く。
	 */
	steps: ([Finite, Finite])[],
	/**
	 *  排出しはじめてからのマスターの通算サンプル数。単調に増える。
	 * 
	 *  画面が古い応答を捨てるための番号ではない。 Channel が順序を保証するので
	 *  （`DEC-PLT-017`）、この経路に古い応答は届かない。進んでいないフレームを
	 *  送らないための比較に使う。
	 * 
	 *  TS では `number` にする。 JS の数値は f64 で、正確に持てるのは 2^53 まで。
	 *  44100 Hz でそこに届くのは 64 億年後なので、精度は落ちない。
	 */
	position: number | null,
};

/**
 *  有限だと分かっている小数。
 * 
 *  specta は素の `f64` を `number | null` に写す。 JSON に NaN も無限も
 *  無いからで、それ自体は正しい。 だが標本数と固定レート（44100）から作る
 *  時間・位置・比は、NaN も無限も作れない。 返り値の位置には属性を書けないので、
 *  「有限だと分かっている」ことを型で言うために1枚被せる。
 * 
 *  中身はそのまま数値として送る（`serde(transparent)`）。
 */
export type Finite = number;

/**
 *  ゲインをどこで触れるか（`TR-REC-14`）。
 * 
 *  これもバックエンドから写さない。理由は [`MicModeView`] と同じ。
 */
export type GainControlView = 
/**  ハードウェア側のボリューム。校正に使える。 */
"Hardware" | 
/**  ソフトウェア実装。校正に使わない（`TR-REC-14`）。 */
"Software" | 
/**  読み書きできない。 */
"Unavailable";

/**  試唱の待ち時間の実測（`TR-SYN-33`）。 */
export type LatencyView = {
	/**  `First` / `Warm` / `Incremental` / `Replay`。 */
	case: string,
	/**  測った回数。 */
	count: number,
	/**  中央値（ミリ秒）。 */
	median_ms: number | null,
	/**  その場面の目標（ミリ秒）。 */
	budget_ms: number,
	/**  収まっているか。回数が少ないうちは `null`。 */
	meets: boolean | null,
};

/**  画面へ返す回り込みの検査結果（`TR-REC-24`）。 */
export type LeakView = {
	/**  見つかった相関（0.0〜1.0）。 */
	correlation: number,
	/**  そのときの遅れ（ミリ秒）。参考値。 */
	lag_ms: number,
	/**  回り込んでいるとみなすか。 */
	leaking: boolean,
};

/**
 *  OS 側の音声加工の状態（`TR-REC-11`）。
 * 
 *  バックエンドの `MicrophoneMode` を写さず、ここで定義する。
 *  書いていない OS では変種が減るので、写すと生成する TS が
 *  ビルドした OS で変わってしまう。 画面の型が OS で変わってはいけない。
 */
export type MicModeView = 
/**  加工なし。これが望ましい。 */
"Standard" | 
/**  音声分離が入っている。 */
"VoiceIsolation" | 
/**  広帯域。 */
"WideSpectrum" | 
/**  判定できなかった。加工が無いことの根拠にはしない。 */
"Unknown";

/**  画面へ返す原音設定の1件（`TR-ALN-33`）。5値をそのまま渡す。 */
export type OtoView = {
	alias: string,
	offset_ms: number,
	consonant_ms: number,
	/**  負なら「offset からの長さ」、正なら「ファイル末尾からの距離」。 */
	cutoff_ms: number,
	preutterance_ms: number,
	overlap_ms: number,
};

/**
 *  出力先の種別（`TR-REC-24`）。
 * 
 *  ドライバの自己申告なので、安全側の根拠にしない。
 *  回り込みは録音側でしか確かめられない。
 */
export type OutputKindView = 
/**  ヘッドホンと申告している。装着されている保証は無い。 */
"Headphones" | 
/**  スピーカと申告している。 */
"Speakers" | 
/**  判定できなかった。 */
"Unknown";

/**  画面へ返す書き出し前の関門（`TR-REC-16`, `TR-REC-32`）。 */
export type PreflightView = {
	/**  NFC へ直した名前の数。 */
	renamed_to_nfc: number,
	/**  それでも NFC でない名前。残っていたら書き出さない。 */
	non_nfc_names: string[],
	/**
	 *  フルスケールに達している採用テイク（行 ID と回数）。
	 * 
	 *  止めない。 本人が承知のうえで配ることはありうる。
	 */
	clipped_takes: ([string, number])[],
	/**  書き出してよいか。 */
	may_export: boolean,
};

/**  画面へ返す進み具合。 */
export type ProgressView = {
	/**  次に録る行の ID。 */
	next_row_id: string | null,
	/**  次に録る行の読み上げ文字列。 */
	next_row_text: string | null,
	/**  収録済み単位。 */
	covered: number,
	/**  必要な単位。 */
	required: number,
	/**  完成状態。 */
	coverage: string,
	/**  手渡し状態。完成判定はこれを見ない（`TR-PKG-33`）。 */
	handoff: string,
	/**  いま歌える曲の数（`TR-RCL-19`）。カバレッジと常に両方出す。 */
	singable_songs: number,
	/**  バンクに入っている曲の数。0 でも成立する。 */
	songs_in_bank: number,
};

/**  画面へ返すプロジェクト。 */
export type ProjectView = {
	/**  不変の識別子。 */
	id: string,
	/**  表示名。manifest が読めなければ `None`。 */
	display_name: string | null,
	method: string | null,
	/**  項目数。 */
	item_count: number | null,
};

/**  画面へ返す「行と、その行のテイク」（`TR-REC-21`, `TR-RCL-25`）。 */
export type RowTakesView = {
	row_id: string,
	/**  読み上げる文字列。 */
	text: string,
	/**  `unrecorded` / `recorded` / `needs_retake` / `excluded`。 */
	state: string,
	/**  世代順。非採用も含む——いつでも採用を戻せる（`TR-REC-21`）。 */
	takes: TakeSummaryView[],
	/**  いま採用しているテイクの ID。 */
	adopted: number | null,
};

/**  画面へ返す曲の状態（`TR-RCL-17`, `TR-RCL-19`, `TR-SYN-20`）。 */
export type SongView = {
	/**  バンクの中でこの曲を指す識別子。位置ではなくこれで指す。 */
	id: string,
	title: string,
	/**  `Complete` / `WithFallback` / `Unavailable`（`TR-RCL-19`）。 */
	singability: string,
	/**  「歌える」に含めてよいか。 */
	singable: boolean,
	/**  必要単位のうち収録済みの数。 */
	covered: number,
	/**  必要単位の数。 */
	required: number,
	/**
	 *  あと何項目録れば完全になるか（`TR-SYN-20`）。
	 * 
	 *  エイリアス名の一覧は返さない。 出すのはこの数。
	 */
	missing_units: number,
	/**  あと何行録れば完全になるか（`TR-RCL-16`, `TR-RCL-17`）。 */
	missing_rows: number,
	/**  その行を録るのに掛かる推定時間（秒、`TR-RCL-09`）。 */
	seconds: number,
	/**  総モーラ数。 */
	total_moras: number,
};

/**  画面へ返す残量の見積もり（`TR-REC-41`）。 */
export type SpaceView = {
	/**  まだ録っていない行の数。 */
	remaining_rows: number,
	/**  その残量で録りきれる件数。「足りません」だけでは判断できない。 */
	rows_that_fit: number,
	/**  残り全部を録りきれるか。 */
	sufficient: boolean,
	/**
	 *  残り全部に要るバイト数。
	 *  必要なバイト数。
	 * 
	 *  TS では `number` にする。 f64 が正確に持てる 2^53 バイトは 9 PB で、そこへ届く前に
	 *  保存先が尽きる。バイト数は `u32` では足りない（4 GB で溢れる）。
	 */
	required_bytes: number | null,
	/**
	 *  保存先の空き。引けなければ `null`。
	 *  保存先の残量（バイト）。取れなければ `None`。
	 */
	available_bytes: number | null,
};

/**  見えている範囲のスペクトログラム（`TR-PLT-04`）。 */
export type SpectrogramView = {
	/**  列を並べた強度（0〜255）。 */
	bins: number[],
	/**  列の数（時間方向）。 */
	columns: number,
	/**  1列あたりの高さ（周波数方向）。 */
	rows: number,
};

/**  画面へ返す試唱の結果（`TR-SYN-18`）。 */
export type SungSongView = {
	title: string,
	phrases: number,
	/**
	 *  鳴らせないので落としたフレーズの数。
	 * 
	 *  落とした位置には無音も別音も代替音も挿さない（`TR-SYN-18` (2)）。
	 */
	dropped_phrases: number,
	/**  鳴らす長さ（ミリ秒）。 */
	duration_ms: number,
};

/**  一覧に出すテイク1件。 */
export type TakeSummaryView = {
	take_id: number,
	/**  何本目か（1 始まり）。 */
	generation: number,
	duration_ms: number,
	/**  取りこぼしで自動的に無効にした（`TR-REC-07`）。 */
	invalid: boolean,
};

/**  画面へ返すテイク。 */
export type TakeView = {
	/**  台帳の ID。 */
	take_id: number,
	row_id: string,
	duration_ms: number,
	/**  絶対値の最大。`koeru_core::analysis::CLIP_THRESHOLD` 以上ならクリップ。 */
	peak: number,
	/**  波形サムネイル（0〜255）。 */
	thumbnail: number[],
	/**  原音設定が導けたか。 */
	has_oto: boolean,
	/**  境界の確信度。 */
	confidence: number | null,
	/**  取りこぼしの回数（`TR-REC-07`）。 */
	discontinuities: number,
	/**  取りこぼしたので自動的に無効にした。 同じフレーズがもう一度出てくる。 */
	invalidated: boolean,
	/**  押した瞬間より前から何ミリ秒ぶん遡れたか（`TR-REC-19`）。 */
	preroll_ms: number,
	/**  サンプルピーク（dBFS）。無音は `null`。 */
	peak_dbfs: number | null,
	/**  発声の前に確保できた無音（ミリ秒、`TR-REC-38`）。 */
	leading_margin_ms: number,
	/**  発声の後に確保できた無音（ミリ秒、`TR-REC-38`）。 */
	trailing_margin_ms: number,
	/**
	 *  前後 300ms の無音マージンを確保できたか（`TR-REC-38`）。
	 *  足りなくてもテイクは有効。 事実を伝えるだけ。
	 */
	has_required_margins: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

