// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  入力デバイスを挙げる。 */
	listDevices: () => typedError<DeviceView[], AppError>(__TAURI_INVOKE("list_devices")),
	/**
	 *  ライブラリの中身を挙げる。
	 * 
	 *  音源ごとに台帳を読む（`Q-RCL-004`）。 名前と項目数だけを返していたときは、
	 *  一覧に到達度も歌える曲も無く、どれを再開すべきかが開くまで分からなかった。
	 */
	listProjects: () => typedError<ProjectView[], AppError>(__TAURI_INVOKE("list_projects")),
	/**
	 *  選べる作り方（`TR-RCL-11`）。
	 * 
	 *  プリセットは `koeru_core::preset` が正本。 数はそこから導く——
	 *  所要時間も到達点も値として持たない（`TR-RCL-01`）。
	 * 
	 *  **収録音高の本数を受け取る。** 方式と音高は別の選択で（`TR-RCL-01`）、
	 *  本数は所要時間にだけ効く。リストは本数を変えても同じ（`TR-RCL-26`）。
	 * 
	 *  **差が5分未満のものを2つ並べない**（`TR-RCL-11`）。並べると、選ぶ側は
	 *  「どちらでもいい」と読む。畳むのは `pace::distinct_offers`。
	 */
	methodPresets: (tones: number) => typedError<MethodPresetView[], AppError>(__TAURI_INVOKE("method_presets", { tones })),
	/**
	 *  収録音高の推奨値（`TR-RCL-06`）。
	 * 
	 *  推奨であって制約ではない。 本数も音高も本人が決める（`TR-RCL-01`）ので、
	 *  ここが返すのは「迷ったらこれ」の出発点だけ。
	 */
	toneSuggestions: () => __TAURI_INVOKE<ToneSuggestionView[]>("tone_suggestions"),
	/**
	 *  選べる収録音高（`TR-RCL-06`, `TR-REC-25`）。
	 * 
	 *  `prefix.map` が覆う C1〜B7 の 84 半音。 これより外は書き出しても
	 *  鳴らす先が無い。画面に MIDI 番号を出さないので、名前を添えて返す。
	 */
	toneOptions: () => __TAURI_INVOKE<ToneOptionView[]>("tone_options"),
	/**
	 *  プロジェクトを作る。
	 * 
	 *  方式プリセットを選ばせる（`TR-RCL-01`, `TR-RCL-11`）。 画面が出した
	 *  [`method_presets`] の `id` をそのまま渡す。
	 * 
	 *  `presamp` は本人が選んだ `presamp.ini` の中身（`DEC-SYN-013`）。 選ばなければ
	 *  `null` で、同梱の既定になる。ここで固定し、あとから変える道は無い。
	 */
	createProject: (displayName: string, presetId: string, tones: number[], presamp: number[] | null) => typedError<string, AppError>(__TAURI_INVOKE("create_project", { displayName, presetId, tones, presamp })),
	/**
	 *  表示名を変える（`DEC-PKG-007`）。
	 * 
	 *  動くのは表示名だけ。 ディレクトリ名は不変の UUID なので、パスは動かない。
	 */
	renameProject: (id: string, displayName: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_project", { id, displayName })),
	/**  開いている音源の環と色（`DEC-PLT-025`, `DEC-PLT-027`）。 */
	voiceState: () => typedError<VoiceStateView, AppError>(__TAURI_INVOKE("voice_state")),
	/**  プロジェクトを開く。 */
	openProject: (id: string) => typedError<ProgressView, AppError>(__TAURI_INVOKE("open_project", { id })),
	/**
	 *  開いたときに戻した `presamp.ini` の中身を残したファイル名（`DEC-SYN-013`）。
	 * 
	 *  戻していなければ `null`。 本人が閉じるまで同じ名前を返す。
	 */
	presampNotice: () => typedError<string | null, AppError>(__TAURI_INVOKE("presamp_notice")),
	/**  戻したことを知らせる札を下ろす（`DEC-SYN-013`）。 */
	dismissPresampNotice: () => typedError<null, AppError>(__TAURI_INVOKE("dismiss_presamp_notice")),
	/**  いまの進み具合。 */
	progress: () => typedError<ProgressView, AppError>(__TAURI_INVOKE("progress")),
	/**
	 *  この音源で選ばれているマイク。
	 * 
	 *  開いたあとに呼ぶ。 台帳から引くので、音源が開いていないと読めない。
	 */
	chosenDevice: () => typedError<ChosenDeviceView, AppError>(__TAURI_INVOKE("chosen_device")),
	/**
	 *  デバイスを選び、ストリームを開く。
	 * 
	 *  返るのは、OS 側の音声加工が残っているかどうか（`TR-REC-11`）。
	 */
	armDevice: (deviceId: string) => typedError<MicModeView, AppError>(__TAURI_INVOKE("arm_device", { deviceId })),
	/**
	 *  入力が届いているかを確かめる（`TR-REC-17`）。
	 * 
	 *  権限が無いと macOS は無音を返す。 成否ではなくピークを見る。
	 */
	probeInput: (ms: number) => typedError<Finite, AppError>(__TAURI_INVOKE("probe_input", { ms })),
	/**  いま録るべき行の収録を始める。 */
	startTake: () => typedError<string, AppError>(__TAURI_INVOKE("start_take")),
	/**
	 *  行を指定して録り直す（`TR-REC-21`, `TR-RCL-25`, `TR-ALN-27`）。
	 * 
	 *  既存のテイクを消さない。 世代を1つ足して積み、採用を新しい方へ切り替える。
	 */
	startRetake: (rowId: string) => typedError<string, AppError>(__TAURI_INVOKE("start_retake", { rowId })),
	rowsWithTakes: () => typedError<RowTakesView[], AppError>(__TAURI_INVOKE("rows_with_takes")),
	/**  いまの録る順と、その並び（`TR-SYN-19`）。 */
	recordingOrder: () => typedError<RecordingOrderView, AppError>(__TAURI_INVOKE("recording_order")),
	/**  録る順を切り替える（`TR-SYN-19` の (b)）。可逆。 */
	setRecordingOrder: (mode: string) => typedError<null, AppError>(__TAURI_INVOKE("set_recording_order", { mode })),
	/**
	 *  採用テイクを切り替える（`TR-RCL-25`）。
	 * 
	 *  カバレッジは変わらない。 変わるのは原音設定の値だけ。
	 */
	adoptTake: (rowId: string, takeId: number) => typedError<null, AppError>(__TAURI_INVOKE("adopt_take", { rowId, takeId })),
	/**  そのテイクの原音設定を、エイリアスごとに引く（`TR-ALN-33`）。 */
	otosOfTake: (takeId: number) => typedError<OtoView[], AppError>(__TAURI_INVOKE("otos_of_take", { takeId })),
	/**
	 *  録れたものをそのまま鳴らす（`TR-REC-43`）。合成を通さない。
	 * 
	 *  返すのは長さ（ミリ秒）。
	 */
	playTake: (takeId: number) => typedError<Finite, AppError>(__TAURI_INVOKE("play_take", { takeId })),
	/**
	 *  いま入ってきている音の包絡を送り続ける（`TR-REC-43`）。
	 * 
	 *  `invoke` で引かせず Channel で送る理由は `DEC-PLT-017`。
	 * 
	 *  この関数が固有に守っているのは2つ。`studio` のロックを取らないので、
	 *  テイクの確定（アライメントを含む）のあいだも波形が止まらない。
	 *  進んでいないフレームは送らないので、同じ絵を描き直させない。
	 */
	streamEnvelope: (onFrame: Channel<EnvelopeView>) => __TAURI_INVOKE<number>("stream_envelope", { onFrame }),
	/**
	 *  波形を送るのをやめる（`TR-REC-43`）。
	 * 
	 *  止める相手を名指しする。 ただ世代を進めるだけにすると、
	 *  画面が作り直されたときに新しい流れを殺してしまう——
	 *  「古いのを止める」と「新しいのを始める」は非同期に飛ぶので、
	 *  後者が先に着くことがある。そのときに数を進めると、生きているほうが止まる。
	 */
	stopEnvelopeStream: (generation: number) => __TAURI_INVOKE<void>("stop_envelope_stream", { generation }),
	/**  収録を止めて、テイクを確定させる。 */
	finishTake: () => typedError<TakeView, AppError>(__TAURI_INVOKE("finish_take")),
	/**  収録済みのテイクを、指定した音高で鳴らす。 */
	preview: (takeId: number, midi: number, lengthMs: Finite) => typedError<number, AppError>(__TAURI_INVOKE("preview", { takeId, midi, lengthMs })),
	/**  プリロールがどれだけ溜まっているか（ミリ秒、`TR-REC-19`）。 */
	prerollMs: () => typedError<number, AppError>(__TAURI_INVOKE("preroll_ms")),
	/**  残量を見積もる（`TR-REC-41`）。 */
	estimateSpace: () => typedError<SpaceView, AppError>(__TAURI_INVOKE("estimate_space")),
	/**
	 *  入力レベルを校正する（`TR-REC-14`）。
	 * 
	 *  関門にしない。 収束しなくても収録に進める。
	 */
	calibrate: (seconds: Finite) => typedError<CalibrationView, AppError>(__TAURI_INVOKE("calibrate", { seconds })),
	/**
	 *  保存してある校正と、いまのゲインの差（`TR-REC-15`）。
	 * 
	 *  勝手に戻さない。 差があることを返すだけ。
	 */
	gainDrift: () => typedError<[Finite, Finite] | null, AppError>(__TAURI_INVOKE("gain_drift")),
	/**  保存してあるゲインへ戻す（`TR-REC-15`）。本人が選んだときだけ呼ぶ。 */
	restoreSavedGain: () => typedError<null, AppError>(__TAURI_INVOKE("restore_saved_gain")),
	/**
	 *  次のフレーズへ進むまでの長さ（ミリ秒、`TR-REC-20`）。
	 * 
	 *  単独音はガイドを使わないので固定長。 発話の検出結果を条件にしない。
	 */
	autoAdvanceMs: () => __TAURI_INVOKE<Finite>("auto_advance_ms"),
	/**
	 *  出力がどこへ出ているらしいか（`TR-REC-24`）。
	 * 
	 *  一次の足切りでしかない。 ドライバの自己申告なので、
	 *  実際の回り込みは [`check_guide_leak`] が録った音で確かめる。
	 */
	outputKind: () => typedError<OutputKindView, AppError>(__TAURI_INVOKE("output_kind")),
	/**
	 *  ガイドを鳴らしながら録って、回り込みを確かめる（`TR-REC-24`）。
	 * 
	 *  これを置かないと、全テイクにガイドが混入した音源が完成に到達しうる。
	 */
	checkGuideLeak: (midi: number) => typedError<LeakView, AppError>(__TAURI_INVOKE("check_guide_leak", { midi })),
	/**
	 *  音高を鳴らす（`TR-REC-23` の音高提示）。
	 * 
	 *  回り込みが確かめられていなければ鳴らさない。
	 */
	playPitch: (midi: number) => typedError<null, AppError>(__TAURI_INVOKE("play_pitch", { midi })),
	/**  曲ごとの状態を、手が届く順に返す（`TR-RCL-17`）。 */
	songStatus: () => typedError<SongView[], AppError>(__TAURI_INVOKE("song_status")),
	/**
	 *  その曲を歌うために、あと録る行（`TR-RCL-17`）。
	 * 
	 *  曲から、その行の収録へ直接入るための口（`DEC-PLT-024` の横移動）。
	 */
	songPlan: (id: string) => typedError<SongPlanView, AppError>(__TAURI_INVOKE("song_plan", { id })),
	/**
	 *  取り込む前に中身を見る（`TR-RCL-12`）。**台帳へ入れない。**
	 * 
	 *  題を決めさせるために要る。 ファイル名から採った候補を返し、
	 *  本人が打ち直してから [`import_songs`] が確定させる。
	 */
	songFilePreview: (bytes: number[], fileName: string) => typedError<SongDraftView[], AppError>(__TAURI_INVOKE("song_file_preview", { bytes, fileName })),
	/**
	 *  UST / USTX を取り込む（`TR-RCL-12`）。主経路はこれ。
	 * 
	 *  **題は本人が決める。** `titles` は [`song_file_preview`] が返した並びと
	 *  同じ長さで、同じ順。空の題は受け取らない。
	 */
	importSongs: (bytes: number[], fileName: string, titles: string[]) => typedError<ImportedSongView[], AppError>(__TAURI_INVOKE("import_songs", { bytes, fileName, titles })),
	/**  曲の題を変える（`TR-RCL-12`）。 */
	renameSong: (id: string, title: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_song", { id, title })),
	/**
	 *  取り込んだ曲すべて（`TR-RCL-12`）。曲バンクを組み替える画面が読む。
	 * 
	 *  歌える曲の一覧（[`song_status`]）とは別。 あちらはバンクの中だけを見せる。
	 */
	allSongs: () => typedError<BankSongView[], AppError>(__TAURI_INVOKE("all_songs")),
	/**
	 *  曲のキーを決める（`TR-SYN-15`, `DEC-SYN-012`）。
	 * 
	 *  **自動では動かさない。** 勧めはするが、当てるのは本人の操作だけ。
	 */
	setSongTranspose: (id: string, semitones: number) => typedError<null, AppError>(__TAURI_INVOKE("set_song_transpose", { id, semitones })),
	/**  曲をバンクから外す／戻す（`TR-RCL-12`）。曲そのものは消さない。 */
	setSongInBank: (id: string, inBank: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_song_in_bank", { id, inBank })),
	/**
	 *  選んだノート群から録音リストを詰め直す（`TR-RCL-16`, `DEC-RCL-011`）。
	 * 
	 *  複数の曲から範囲を選べる。 返すのは足した行の数。
	 */
	repackForSelection: (selections: SongSelection[]) => typedError<number, AppError>(__TAURI_INVOKE("repack_for_selection", { selections })),
	/**  曲のノート列（`TR-RCL-12`）。範囲を選ぶ画面が読む。 */
	songNotes: (id: string) => typedError<NoteView[], AppError>(__TAURI_INVOKE("song_notes", { id })),
	/**
	 *  曲を歌わせる（`TR-SYN-01`〜`04`, `TR-SYN-18`）。
	 * 
	 *  先頭フレーズができた時点で鳴りはじめる。 曲全体の合成を待たない。
	 */
	singSong: (id: string) => typedError<SungSongView, AppError>(__TAURI_INVOKE("sing_song", { id })),
	/**
	 *  背後で待っている仕事の数（`TR-SYN-33`, `TR-SYN-34`）。
	 * 
	 *  「録音終了 → 試唱ボタン活性化」の間に、無言の待ち時間を作らない。
	 *  画面はこれを見て、進んでいることを出す。
	 */
	pendingWork: () => typedError<number, AppError>(__TAURI_INVOKE("pending_work")),
	/**  試唱の待ち時間を返す（`TR-SYN-33`）。 */
	latencyReport: () => typedError<LatencyView[], AppError>(__TAURI_INVOKE("latency_report")),
	/**
	 *  見えている範囲の波形（`TR-PLT-04`）。
	 * 
	 *  上下の組を画素数ぶん返す。 読む量は画素数に比例し、範囲の広さには比例しない。
	 */
	waveformWindow: (takeId: number, fromMs: Finite, toMs: Finite, pixels: number) => typedError<([Finite, Finite])[], AppError>(__TAURI_INVOKE("waveform_window", { takeId, fromMs, toMs, pixels })),
	/**
	 *  見えている範囲のスペクトログラムを作る（`TR-PLT-04`）。
	 * 
	 *  素材ファイル全体を先に計算しない。
	 */
	spectrogramWindow: (takeId: number, fromMs: Finite, toMs: Finite, columns: number, rows: number) => typedError<SpectrogramView, AppError>(__TAURI_INVOKE("spectrogram_window", { takeId, fromMs, toMs, columns, rows })),
	/**  書き出す前の関門（`TR-REC-16`, `TR-REC-32`）。 */
	preflight: () => typedError<PreflightView, AppError>(__TAURI_INVOKE("preflight")),
	/**
	 *  全チャンネルを混ぜる（`TR-REC-06`）。
	 * 
	 *  全チャンネルに有意な信号があるときだけ選べる。
	 */
	useMixedChannels: () => typedError<null, AppError>(__TAURI_INVOKE("use_mixed_channels")),
	/**  鳴らしている音を止める。 */
	stopPreview: () => typedError<null, AppError>(__TAURI_INVOKE("stop_preview")),
	/**  確認の進み具合を読む。 */
	reviewSummary: () => typedError<ReviewSummaryView, AppError>(__TAURI_INVOKE("review_summary")),
	/**
	 *  採用テイクのエントリ全部を、手が届く順に（`TR-ALN-26`）。
	 * 
	 *  確認待ちが先、済んだものが後ろ。 確定したものも返すのは、固定が
	 *  そのあとも残るため（`REQ-ALN-007`）。
	 */
	reviewQueue: () => typedError<ReviewItemView[], AppError>(__TAURI_INVOKE("review_queue")),
	/**  1件ずつ確認して確定させる（`REQ-ALN-008`）。 */
	confirmEntry: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("confirm_entry", { key })),
	/**  まとめて確認する（`REQ-ALN-010`）。返るのは確定させた件数。 */
	confirmAllEntries: () => typedError<number, AppError>(__TAURI_INVOKE("confirm_all_entries")),
	/**
	 *  個別確認をやめる（`REQ-ALN-010`, `INV-ALN-004`）。
	 * 
	 *  `mode` は `batch` か `suggest_rerecord`。上限を超えていなければ通らない。
	 */
	switchReviewMode: (mode: string) => typedError<null, AppError>(__TAURI_INVOKE("switch_review_mode", { mode })),
	/**
	 *  5値のどれかを人が直す。その値だけを固定する（`REQ-ALN-005`, `TR-ALN-30`）。
	 * 
	 *  `slot` は `offset` / `consonant` / `cutoff` / `preutterance` / `overlap`。
	 */
	editOtoValue: (key: string, slot: string, value: Finite) => typedError<null, AppError>(__TAURI_INVOKE("edit_oto_value", { key, slot, value })),
	/**  固定を解いて自動へ戻す（`REQ-ALN-006`）。 */
	revertOtoValue: (key: string, slot: string) => typedError<null, AppError>(__TAURI_INVOKE("revert_oto_value", { key, slot })),
	/**  oto を直すのではなく録り直す（`REQ-ALN-009`, `TR-ALN-27`）。 */
	rerecordEntry: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("rerecord_entry", { key })),
	/**
	 *  書き出し前の検証（`TR-ALN-20`）。
	 * 
	 *  返るのは `(直した件数, 止まっているエイリアス)`。
	 */
	validateOtos: () => typedError<[number, string[]], AppError>(__TAURI_INVOKE("validate_otos")),
	/**
	 *  `oto.ini` を書き出す（`TR-ALN-21`, `REQ-PKG-003`）。
	 * 
	 *  確認が残っている間は通らない（`INV-ALN-003`）。
	 * 
	 *  `encoding` は `cp932`（既定）か `utf8`。 知らない名前は既定へ倒す
	 *  ——書き出しを止めるほどのことではなく、既定が UTAU 互換だから。
	 */
	exportOtos: (encoding: string) => typedError<string, AppError>(__TAURI_INVOKE("export_otos", { encoding })),
	/**  モデルが変わったせいで古くなった推定（`TR-ALN-29`）。返るのは行 ID。 */
	staleTakes: () => typedError<string[], AppError>(__TAURI_INVOKE("stale_takes")),
	/**  同梱しているモデルのライセンス表記（`TR-ALN-31`）。 */
	modelNotice: () => typedError<string, AppError>(__TAURI_INVOKE("model_notice")),
	/**  配布に出す値を読む。 */
	packageSettings: () => typedError<PackageSettingsView, AppError>(__TAURI_INVOKE("package_settings")),
	/**
	 *  配布に出す値を保存する。
	 * 
	 *  画像は触らない。 別の口で入れたものを、ここで消してしまわない。
	 */
	setPackageSettings: (input: PackageSettingsView) => typedError<null, AppError>(__TAURI_INVOKE("set_package_settings", { input })),
	/**
	 *  音源アイコンの元画像を入れ替える（`TR-PKG-07`, `DEC-PKG-012`）。
	 * 
	 *  受け取った時点で 100×100 の BMP にできるかを確かめる。 書き出しまで
	 *  黙っていると、選んだ画像が使えないことに最後の一歩で気づく。
	 */
	setPackageIcon: (bytes: number[] | null) => typedError<null, AppError>(__TAURI_INVOKE("set_package_icon", { bytes })),
	/**
	 *  立ち絵を入れ替える（`TR-PKG-07`）。
	 * 
	 *  受け取った時点で PNG へ揃える。 配布物に入る名前は `portrait.png` に
	 *  固定してあるので、JPEG をそのまま持つと中身と拡張子が食い違う。
	 *  読めない画像もここで断る——書き出しまで黙っていると、最後の一歩で気づく。
	 */
	setPackagePortrait: (bytes: number[] | null) => typedError<null, AppError>(__TAURI_INVOKE("set_package_portrait", { bytes })),
	/**  音源アイコンの元画像を返す。選んでいなければ `None`。 */
	packageIcon: () => typedError<number[] | null, AppError>(__TAURI_INVOKE("package_icon")),
	/**  立ち絵を返す。選んでいなければ `None`。 */
	packagePortrait: () => typedError<number[] | null, AppError>(__TAURI_INVOKE("package_portrait")),
	/**  いま書き出せるか（`TR-PKG-49`, `TR-PKG-51`）。 */
	packageState: () => typedError<PackageStateView, AppError>(__TAURI_INVOKE("package_state")),
	/**  配布物に入るファイルの一覧（`TR-PKG-28` の同梱物）。 */
	packageContents: () => typedError<PackageFileView[], AppError>(__TAURI_INVOKE("package_contents")),
	/**
	 *  書き出す（`REQ-PKG-105`, `REQ-PKG-106`）。
	 * 
	 *  版の札は受け取らない。 配布に出す値として保存してあるものを使う。
	 */
	exportPackage: () => typedError<ExportedView, AppError>(__TAURI_INVOKE("export_package")),
	/**
	 *  下位方式へ書き出す（`TR-PKG-23`, `TR-PKG-24`, `TR-PKG-25`）。
	 * 
	 *  独立した音源ルート・独立した ZIP。 同一 ZIP へ同梱しない。
	 *  5値は対象方式の規約プリセットで作り直す（`TR-ALN-34`）。
	 * 
	 *  受け取るのは作り方の識別子だけ。 出せるかどうかは Rust が被覆から判定する
	 *  ——画面の関門を通らずに叩かれても素通りさせない。
	 */
	exportDowngrade: (method: string) => typedError<ExportedView, AppError>(__TAURI_INVOKE("export_downgrade", { method })),
	/**  書き出しの履歴（`TR-PKG-44`）。新しい順。 */
	releases: () => typedError<ReleaseView[], AppError>(__TAURI_INVOKE("releases")),
	/**
	 *  書き出したものを、OS のファイルマネージャで見せる（`TR-PKG-45`）。
	 * 
	 *  渡すのは連番だけ。 在り処は Rust が台帳から引く。
	 */
	revealRelease: (seq: number) => typedError<null, AppError>(__TAURI_INVOKE("reveal_release", { seq })),
};

/* Types */
/**  画面へ返す失敗。 */
export type AppError = {
	code: string,
	class: FailureClass,
	/**  操作が確定したかどうか。 分類からの既定を、確定した工程を知る持ち主が上書きする。 */
	outcome: FailureOutcome,
	action: FailureAction,
	message: string,
};

/**  曲バンクの1曲（`TR-RCL-12`）。 */
export type BankSongView = {
	id: string,
	title: string,
	/**  ノートの数。休符は入らない。 */
	notes: number,
	/**  曲バンクに入っているか（`TR-RCL-12`）。 */
	in_bank: boolean,
	/**  利用許諾（`TR-RCL-12` (f)）。 */
	license: string,
};

/**  画面へ返す校正の結果（`TR-REC-14`）。 */
export type CalibrationView = {
	/**  決めたゲイン（0.0〜1.0）。触れなければ `null`。 */
	gain: number | null,
	/**
	 *  `hardware` / `software` / `unavailable`。
	 * 
	 *  `hardware` 以外では自動調整しない（`TR-REC-14`）。
	 *  画面は OS 設定での調整を1回だけ案内する。
	 */
	control: GainControlView,
	/**  最後に測ったピーク（dBFS）。無音は `null`。 */
	peak_dbfs: number | null,
	/**  目標範囲（-12〜-6 dBFS）に入ったか。入らなくても収録には進める。 */
	settled: boolean,
};

/**  この音源で選ばれているマイク（`TR-REC-03`）。 */
export type ChosenDeviceView = {
	/**  選ばれているマイクの識別子。一度も選んでいなければ `None`。 */
	id: string | null,
	/**  いまストリームが開いているか。開いていなければ、録る前に開き直す。 */
	armed: boolean,
	/**  いま収録中か。面を移った先でも「止める」を出すのに要る。 */
	recording: boolean,
};

/**  画面へ返すデバイス。 */
export type DeviceView = {
	/**  永続識別子（`TR-REC-03`）。同一性の判定はこれで行う。 */
	id: string,
	/**  表示名。一覧に出すためだけ。 */
	name: string,
};

/**  下位方式の書き出し1件（`TR-PKG-24`, `TR-PKG-25`）。 */
export type DowngradeView = {
	/**  書き出す作り方。 */
	method: string,
	/**
	 *  複製される WAV の概算バイト数。
	 * 
	 *  **「oto.ini 1ファイル分」ではない。** 元とほぼ同等の容量がもう1本できる。
	 * 
	 *  `u32` に畳まない。 **畳んでいた**ので 4 GiB で頭打ちになり、多音階の
	 *  大きな音源ほど「増える容量」が小さく出ていた——警告のための数が、
	 *  いちばん警告したい場面で嘘をつく。小数なら 2^53 バイトまで正確に届く。
	 */
	bytes: Finite,
};

/**  画面へ返す、いま流れている音の包絡（`TR-REC-43`）。 */
export type EnvelopeView = {
	/**
	 *  目盛りごとの min/max。畳まずにそのまま渡す。
	 * 
	 *  割り切れない本数へ畳むと絵が揺れる。 画面は1本につき1列を描く。
	 */
	steps: ([Finite, Finite])[],
	/**
	 *  排出しはじめてからのマスターの通算サンプル数。単調に増える。
	 * 
	 *  画面が古い応答を捨てるための番号ではない。 Channel が順序を保証するので
	 *  （`DEC-PLT-017`）、この経路に古い応答は届かない。進んでいないフレームを
	 *  送らないための比較に使う。
	 * 
	 *  TS では `number` にする。 JS の数値は f64 で、正確に持てるのは 2^53 まで。
	 *  44100 Hz でそこに届くのは 64 億年後なので、精度は落ちない。
	 */
	position: number | null,
	/**
	 *  ストリームを開いてから、フルスケールに達した回数（`TR-REC-16` の定義）。
	 * 
	 *  **画面に数えさせない。** `steps` は 1.5 秒ぶんの窓を丸ごと渡すので、
	 *  1つの割れが 30 回ぶんの通知に残る——通知ごとに「窓が割れているか」を
	 *  数えると、**割れた回数ではなく更新の回数**になる。**踏んだ。**
	 * 
	 *  `Number` を通す。 素の `f64` は `number | null` に写るので
	 *  （`react-conventions`）、回数としては受け取りにくい。
	 */
	clipped_runs: number,
};

/**
 *  書き出した結果（`TR-PKG-44`）。
 * 
 *  **在り処は返さない**（`TR-PKG-45`）。 通常モードの画面にパスを出さない。
 *  置き場所を見せる経路は [`reveal_release`] が持ち、受け渡すのは連番だけ。
 */
export type ExportedView = {
	seq: number,
	archive_name: string,
	alias_count: number,
	released_at: string,
};

/**  [`Action`] の写し。 */
export type FailureAction = "fix_input" | "meet_condition" | "refresh" | "nothing" | "show_receipt" | "wait" | "reconnect" | "grant" | "retry_same" | "free_space" | "recover" | "use_available" | "rebuild" | "report";

/**  [`Class`] の写し。 */
export type FailureClass = "invalid_input" | "rejected" | "conflict" | "cancelled" | "already_committed" | "busy" | "device_unavailable" | "transient_io" | "storage" | "corrupt" | "unsupported" | "engine_failed" | "internal";

/**  [`Outcome`] の写し。 */
export type FailureOutcome = "not_started" | "not_committed" | "committed" | "unknown";

/**
 *  検証で見つかった1件（`TR-PKG-49`, `TR-PKG-51`）。
 * 
 *  文面は画面が持つ。 ここが返すのは種別と、どこの話かだけ。
 */
export type FindingView = {
	/**  音源ルートからの相対パス。 */
	file: string,
	alias: string | null,
	/**  その行の録った回へ入るための行 ID（`TR-PKG-51`）。 */
	row_id: string | null,
	/**  種別。文面の対応は画面が持つ。 */
	kind: string,
	/**  数値を伴うものだけ。 */
	detail: string | null,
};

/**
 *  有限だと分かっている小数。
 * 
 *  specta は素の `f64` を `number | null` に写す。 JSON に NaN も無限も
 *  無いからで、それ自体は正しい。 だが標本数と固定レート（44100）から作る
 *  時間・位置・比は、NaN も無限も作れない。 返り値の位置には属性を書けないので、
 *  「有限だと分かっている」ことを型で言うために1枚被せる。
 * 
 *  中身はそのまま数値として送る（`serde(transparent)`）。
 */
export type Finite = number;

/**
 *  ゲインをどこで触れるか（`TR-REC-14`）。
 * 
 *  これもバックエンドから写さない。理由は [`MicModeView`] と同じ。
 */
export type GainControlView = 
/**  ハードウェア側のボリューム。校正に使える。 */
"Hardware" | 
/**  ソフトウェア実装。校正に使わない（`TR-REC-14`）。 */
"Software" | 
/**  読み書きできない。 */
"Unavailable";

/**
 *  取り込んだ曲（`TR-RCL-12`）。
 * 
 *  題をそのまま返す。 取り込んだ直後に本人が直せるようにするため、
 *  一覧を引き直さずに出せる形で返す。
 */
export type ImportedSongView = {
	id: string,
	title: string,
	/**  ノートの数。休符は入らない。 */
	notes: number,
};

/**  試唱の待ち時間の実測（`TR-SYN-33`）。 */
export type LatencyView = {
	/**  `First` / `Warm` / `Incremental` / `Replay`。 */
	case: string,
	/**  測った回数。 */
	count: number,
	/**  中央値（ミリ秒）。 */
	median_ms: number | null,
	/**  その場面の目標（ミリ秒）。 */
	budget_ms: number,
	/**  収まっているか。回数が少ないうちは `null`。 */
	meets: boolean | null,
};

/**  画面へ返す回り込みの検査結果（`TR-REC-24`）。 */
export type LeakView = {
	/**  見つかった相関（0.0〜1.0）。 */
	correlation: number,
	/**  そのときの遅れ（ミリ秒）。参考値。 */
	lag_ms: number,
	/**  回り込んでいるとみなすか。 */
	leaking: boolean,
};

/**
 *  画面へ返す方式プリセット1つ（`TR-RCL-11`）。
 * 
 *  選ぶときだけオブジェクトになるもの（`docs/reports/ux/ooui-model.md`）。
 *  選ばれたら音源の属性に落ちるので、永続する実体を持たない。
 */
export type MethodPresetView = {
	/**  方式の識別子。画面に出さない——出すのは `label` のほう。 */
	id: string,
	label: string,
	/**  ひとことで何をする方式か。 */
	summary: string,
	/**  読み上げる行の数。 */
	rows: number,
	/**  そこから取れる音の数。カバレッジの分母になる。 */
	units: number,
	/**  全部読み終えるまでの見積もり（秒、`TR-RCL-09`）。 */
	seconds: number,
	/**  何周録るか。音階の数（`TR-RCL-26`）。 */
	passes: number,
	/**  読み終えると何ができるか（`TR-RCL-11` の到達点）。 */
	reach: string,
	/**  読み上げの難しさ（`TR-RCL-11`）。良し悪しではなく、何が起きるかを書く。 */
	reading: string,
};

/**
 *  OS 側の音声加工の状態（`TR-REC-11`）。
 * 
 *  バックエンドの `MicrophoneMode` を写さず、ここで定義する。
 *  書いていない OS では変種が減るので、写すと生成する TS が
 *  ビルドした OS で変わってしまう。 画面の型が OS で変わってはいけない。
 */
export type MicModeView = 
/**  加工なし。これが望ましい。 */
"Standard" | 
/**  音声分離が入っている。 */
"VoiceIsolation" | 
/**  広帯域。 */
"WideSpectrum" | 
/**  判定できなかった。加工が無いことの根拠にはしない。 */
"Unknown";

/**  ノートの範囲（`[from, to)`）。 */
export type NoteRange = {
	from: number,
	to: number,
};

/**  曲の1ノート（`TR-RCL-12` (a)(b)）。 */
export type NoteView = {
	/**  歌詞（1モーラぶん）。 */
	lyric: string,
	/**  音の高さ。英語音名（`TR-REC-25`）。 */
	tone: string,
	/**  長さ（ティック）。480 が4分音符。 */
	ticks: number,
};

/**  画面へ返す原音設定の1件（`TR-ALN-33`）。5値をそのまま渡す。 */
export type OtoView = {
	alias: string,
	offset_ms: number,
	consonant_ms: number,
	/**  負なら「offset からの長さ」、正なら「ファイル末尾からの距離」。 */
	cutoff_ms: number,
	preutterance_ms: number,
	overlap_ms: number,
};

/**
 *  出力先の種別（`TR-REC-24`）。
 * 
 *  ドライバの自己申告なので、安全側の根拠にしない。
 *  回り込みは録音側でしか確かめられない。
 */
export type OutputKindView = 
/**  ヘッドホンと申告している。装着されている保証は無い。 */
"Headphones" | 
/**  スピーカと申告している。 */
"Speakers" | 
/**  判定できなかった。 */
"Unknown";

/**  配布物に入るファイル1つ。 */
export type PackageFileView = {
	path: string,
	/**  配布物に入るときの大きさ（バイト）。 */
	bytes: number,
};

/**
 *  配布に出す値（`TR-PKG-02`, `TR-PKG-28`, `DEC-PKG-008`）。
 * 
 *  画像そのものは返さない。 アイコンと立ち絵は別の口で取る——
 *  設定を1秒ごとに引く画面で、数 MB の画像を毎回運ばない。
 */
export type PackageSettingsView = {
	/**  音源ルートフォルダ名。ASCII 固定（`DEC-PKG-008`）。 */
	distribution_name: string,
	/**  書き出しプロファイル（`TR-PKG-12`）。 */
	profile: string,
	author: string | null,
	voice: string | null,
	sample: string | null,
	web: string | null,
	version: string | null,
	/**  音源アイコンを選んであるか（`TR-PKG-07`）。 */
	has_icon: boolean,
	/**  立ち絵を選んであるか（`TR-PKG-07`）。 */
	has_portrait: boolean,
	portrait_opacity: number,
	portrait_height: number,
	tone_range_note: string | null,
	/**  利用規約の本文（`DEC-PKG-011`）。未記入でも書き出しを止めない。 */
	terms: string | null,
	credit_example: string | null,
	contact: string | null,
	disclaimer: string | null,
	character_note: string | null,
};

/**  いま書き出せるか（`TR-PKG-49`）。 */
export type PackageStateView = {
	may_export: boolean,
	profile: string,
	/**  使える書き出し方。CP932 が壊れていれば減る（`TR-PKG-13`）。 */
	available_profiles: string[],
	/**  配布物に入るファイルの数。 */
	file_count: number,
	alias_count: number,
	/**  そのまま出せる方式（`INV-PKG-105`）。 */
	exportable_methods: string[],
	/**  この音源の方式に足りていない呼び名（`TR-PKG-23`）。全件返す。 */
	missing_aliases: string[],
	/**
	 *  この作り方に必要な音の表を持っているか（`TR-RCL-02`）。
	 * 
	 *  持っていない作り方では被覆を確かめられないので、書き出せない。
	 */
	required_table_known: boolean,
	/**
	 *  原音設定の確認が済んでいるか（`INV-ALN-003`）。
	 * 
	 *  素材の名前（`TR-REC-32`）はここに入らない。`preflight` が持つ。
	 */
	otos_ready: boolean,
	findings: FindingView[],
	unencodable: UnencodableView[],
	/**  下位方式への書き出し（`TR-PKG-24`, `TR-PKG-25`）。 */
	downgrades: DowngradeView[],
};

/**  画面へ返す「あと録る行」1件（`TR-RCL-17`）。 */
export type PlanRowView = {
	/**  行の識別子。**画面に出さない**（`TR-REC-18`）——録りに行くときに渡すだけ。 */
	row_id: string,
	/**  読み上げる文字列。 */
	text: string,
	/**  この行から取れる音の数。 */
	units: number,
};

/**  画面へ返す書き出し前の関門（`TR-REC-16`, `TR-REC-32`）。 */
export type PreflightView = {
	/**  NFC へ直した名前の数。 */
	renamed_to_nfc: number,
	/**  それでも NFC でない名前。残っていたら書き出さない。 */
	non_nfc_names: string[],
	/**
	 *  フルスケールに達している採用テイク（行 ID と回数）。
	 * 
	 *  止めない。 本人が承知のうえで配ることはありうる。
	 */
	clipped_takes: ([string, number])[],
	/**  書き出してよいか。 */
	may_export: boolean,
};

/**  画面へ返す進み具合。 */
export type ProgressView = {
	/**  次に録る行の ID。 */
	next_row_id: string | null,
	/**  次に録る行の読み上げ文字列。 */
	next_row_text: string | null,
	/**  収録済み単位。 */
	covered: number,
	/**  必要な単位。 */
	required: number,
	/**  完成状態。 */
	coverage: string,
	/**  手渡し状態。完成判定はこれを見ない（`TR-PKG-33`）。 */
	handoff: string,
	/**  いま歌える曲の数（`TR-RCL-19`）。カバレッジと常に両方出す。 */
	singable_songs: number,
	/**  バンクに入っている曲の数。0 でも成立する。 */
	songs_in_bank: number,
	/**
	 *  残り所要時間（秒、`TR-RCL-09`）。
	 * 
	 *  固定の見積もり。 実測では書き換えない（`DEC-RCL-013`）。
	 */
	remaining_seconds: number,
	/**
	 *  残りの行数（`TR-RCL-09`）。多音階では音高の本数を掛けた数。
	 * 
	 *  時間と並べて出す。 時間は桁しか合っていないが、行数は数え上げなので正確。
	 */
	remaining_rows: number,
	/**
	 *  音高ごとの消化率（`TR-RCL-26`）。単音階では1件。
	 * 
	 *  詳細表示に置く欄。 `singable_songs` は音高を跨いだ実際の判定結果で、
	 *  これを足し合わせたものではない——1音高だけ録り終えても、
	 *  音域の広い曲は歌えない。
	 */
	by_tone: ToneProgressView[],
};

/**  画面へ返すプロジェクト。 */
export type ProjectView = {
	/**  不変の識別子。 */
	id: string,
	/**  表示名。manifest が読めなければ `None`。 */
	display_name: string | null,
	method: string | null,
	/**  項目数。 */
	item_count: number | null,
	/**  育ち具合。台帳を読めなければ `None`。 */
	state: VoiceStateView | null,
};

/**
 *  全部の行と、そのテイク（`TR-REC-21`, `TR-RCL-25`）。
 *  録る順（`TR-SYN-19`）。
 */
export type RecordingOrderView = {
	/**
	 *  いまのモード。`SongBankFirst` か `CoverageEfficiency`。
	 * 
	 *  **どちらでいるかを常に表示する**（`TR-SYN-19`）。
	 */
	mode: string,
	/**  次に録る順の行 ID。収録済みの行は入らない。 */
	row_ids: string[],
};

/**  書き出しの履歴1件（`TR-PKG-44`）。 */
export type ReleaseView = {
	seq: number,
	version: string,
	method: string,
	alias_count: number,
	validation: string,
	archive_name: string,
	released_at: string,
};

/**  確認キューの1件（`TR-ALN-26`）。 */
export type ReviewItemView = {
	/**
	 *  このエントリを指す鍵。確認・編集・録り直しに渡す。
	 * 
	 *  **`oto.alias` では指せない。** 多音階は同じ綴りを音高の数だけ持つ
	 *  （`TR-ALN-22`）。中身を読まずにそのまま返す文字列として扱う。
	 */
	key: string,
	/**  そのエイリアスを録った行。一覧の絞り込みに要る（`DEC-PLT-024`）。 */
	row_id: string,
	/**  自動推定した5値（`TR-ALN-26` (2)）。エイリアスはこの中にある。 */
	oto: OtoView,
	/**  低確信度の主因（`TR-ALN-26` (3)）。内訳を持たなければ `null`。 */
	cause: string | null,
	confidence: number,
	/**  `not_estimated` | `auto_confirmed` | `in_queue` | `blocked`。 */
	state: string,
	/**
	 *  固定されている値の名前（`TR-ALN-30`）。
	 * 
	 *  真偽の5つ組で渡さない。 画面が並びを覚えることになり、
	 *  5値の順序が `oto.ini` と違う（`koeru_align::ini`）ことが二度目の取り違えを呼ぶ。
	 */
	pinned: string[],
};

/**  確認の進み具合（`TR-ALN-25`, `TR-ALN-28`）。 */
export type ReviewSummaryView = {
	/**  `individual` | `batch` | `suggest_rerecord`。 */
	mode: string,
	/**  確認待ちの件数。 */
	pending: number,
	/**  検証で止まっている件数（`TR-ALN-20`）。 */
	blocked: number,
	/**  確認にかかる見積もりの合計（秒）。 */
	estimated_seconds: number,
	/**  上限（秒）。`DEC-ALN-003` の合計5分。 */
	budget_seconds: number,
	/**  上限を超えているか。超えるまで個別確認をやめられない（`INV-ALN-004`）。 */
	exceeds_budget: boolean,
	/**  切り出しが1つも取れていない行の数。キューには現れないが書き出しは止まる。 */
	missing: number,
	/**  WAV をまたいで重なっているエイリアスの数。重なると片方が確認から落ちる。 */
	conflicting: number,
	/**  まだ推定していないエントリの数。録り直しに回したものがここにいる。 */
	unestimated: number,
	/**  いま書き出してよいか。画面はこれを見る（件数から組み立て直さない）。 */
	may_export: boolean,
	/**  確認を飛ばせる経路を必ず出す方式か（`TR-ALN-28`）。 */
	allows_skipping: boolean,
	/**  その方式の到達水準。 */
	reach: string,
	exported: boolean,
};

/**
 *  環1本（`DEC-PLT-025`）。五十音の行ごとの被覆。
 * 
 *  名前を持たない。 環に要るのは順番と数だけで、行の名前は画面に出す
 *  文字列ではない（`TR-REC-18`）。
 */
export type RingView = {
	covered: number,
	total: number,
};

/**  画面へ返す「行と、その行のテイク」（`TR-REC-21`, `TR-RCL-25`）。 */
export type RowTakesView = {
	row_id: string,
	/**  読み上げる文字列。 */
	text: string,
	/**  `unrecorded` / `recorded` / `needs_retake` / `excluded`。 */
	state: string,
	/**  この行から取れる音の数。カバレッジは行ではなくこれで数える（`TR-RCL-19`）。 */
	units: number,
	/**  世代順。非採用も含む——いつでも採用を戻せる（`TR-REC-21`）。 */
	takes: TakeSummaryView[],
	/**  いま採用しているテイクの ID。 */
	adopted: number | null,
	/**  その行のモーラ数（`TR-RCL-07`）。境界の区切りの数と一致する。 */
	moras: number,
	/**
	 *  難読音の数（`TR-RCL-07`）。拗音かつ外来音の拍。
	 * 
	 *  スコアの合成値は返さない。 重みに根拠が無いので、
	 *  絶対値を画面に出さない（`TR-RCL-07` の `RowRisk`）。
	 */
	risk_hard: number,
};

/**  取り込む前の1曲（`TR-RCL-12`）。まだ台帳に無い。 */
export type SongDraftView = {
	/**
	 *  ファイル名（と、複数あればトラック名）から採った題の候補。
	 * 
	 *  **空のことがある。** そのときは入力欄も空で出し、本人に打たせる。
	 */
	title_hint: string,
	/**  ノートの数。休符は入らない。 */
	notes: number,
	/**  いちばん低い音。ノートが無ければ `null`。 */
	low: string | null,
	/**  いちばん高い音。 */
	high: string | null,
};

/**  画面へ返す「その曲を歌うための計画」（`TR-RCL-16`, `TR-RCL-17`）。 */
export type SongPlanView = {
	rows: PlanRowView[],
	/**  これで埋まる音の数。 */
	covers: number,
	/**  どの行にも無くて埋まらない音の数。0 でなければ、その作り方では歌えない。 */
	unreachable: number,
	/**  読むのに掛かる見積もり（秒、`TR-RCL-09`）。 */
	seconds: Finite,
};

/**  1曲ぶんの選択（`TR-RCL-12`）。 */
export type SongSelection = {
	song_id: string,
	/**  選んだノートの範囲。空なら曲全体。 */
	ranges: NoteRange[],
};

/**  画面へ返す曲の状態（`TR-RCL-17`, `TR-RCL-19`, `TR-SYN-20`）。 */
export type SongView = {
	/**  バンクの中でこの曲を指す識別子。位置ではなくこれで指す。 */
	id: string,
	title: string,
	/**  `Complete` / `WithFallback` / `Unavailable`（`TR-RCL-19`）。 */
	singability: string,
	/**  「歌える」に含めてよいか。 */
	singable: boolean,
	/**  必要単位のうち収録済みの数。 */
	covered: number,
	/**  必要単位の数。 */
	required: number,
	/**
	 *  あと何項目録れば完全になるか（`TR-SYN-20`）。
	 * 
	 *  エイリアス名の一覧は返さない。 出すのはこの数。
	 */
	missing_units: number,
	/**  あと何行録れば完全になるか（`TR-RCL-16`, `TR-RCL-17`）。 */
	missing_rows: number,
	/**  その行を録るのに掛かる推定時間（秒、`TR-RCL-09`）。 */
	seconds: number,
	/**
	 *  収録音高から近いか（`TR-SYN-15`）。
	 * 
	 *  **偽でも鳴らせる。** 基準の ±7 半音・二乗平均 4 半音に実測の裏付けが
	 *  無い（`DEC-SYN-012`）ので、押せなくするのではなく、どうなるかを先に言う。
	 */
	previewable: boolean,
	/**
	 *  いま指定されているキー（半音、`TR-SYN-15`）。0 なら書かれた調のまま。
	 * 
	 *  **自動では動かない。** 変わるのは本人が `set_song_transpose` を
	 *  呼んだときだけ（`DEC-SYN-012`）。
	 */
	transpose: number,
	/**  勧めるキー（半音、`TR-SYN-15`）。当てていない。提示するだけ。 */
	recommended_transpose: number,
	/**
	 *  足すといまのキーのまま届くようになる収録音高（`TR-RCL-22`）。
	 * 
	 *  届いているなら `null`。 英語音名で返す——画面に MIDI 番号を出さない。
	 */
	rescuing_tone: string | null,
	/**  総モーラ数。 */
	total_moras: number,
};

/**  画面へ返す残量の見積もり（`TR-REC-41`）。 */
export type SpaceView = {
	/**  まだ録っていない行の数。 */
	remaining_rows: number,
	/**  その残量で録りきれる件数。「足りません」だけでは判断できない。 */
	rows_that_fit: number,
	/**  残り全部を録りきれるか。 */
	sufficient: boolean,
	/**
	 *  残り全部に要るバイト数。
	 *  必要なバイト数。
	 * 
	 *  TS では `number` にする。 f64 が正確に持てる 2^53 バイトは 9 PB で、そこへ届く前に
	 *  保存先が尽きる。バイト数は `u32` では足りない（4 GB で溢れる）。
	 */
	required_bytes: number | null,
	/**
	 *  保存先の空き。引けなければ `null`。
	 *  保存先の残量（バイト）。取れなければ `None`。
	 */
	available_bytes: number | null,
};

/**  見えている範囲のスペクトログラム（`TR-PLT-04`）。 */
export type SpectrogramView = {
	/**  列を並べた強度（0〜255）。 */
	bins: number[],
	/**  列の数（時間方向）。 */
	columns: number,
	/**  1列あたりの高さ（周波数方向）。 */
	rows: number,
};

/**  区画が切り替わった1箇所（`TR-SYN-16`）。 */
export type SubbankSwitchView = {
	/**  切り替わった音符の位置（0 始まり）。 */
	note_index: number,
	/**  直前まで使っていた音の高さ。英語音名（`TR-REC-25`）。 */
	from: string | null,
	/**  ここから使う音の高さ。 */
	to: string | null,
};

/**  画面へ返す試唱の結果（`TR-SYN-18`）。 */
export type SungSongView = {
	title: string,
	phrases: number,
	/**
	 *  鳴らせないので落としたフレーズの数。
	 * 
	 *  落とした位置には無音も別音も代替音も挿さない（`TR-SYN-18` (2)）。
	 */
	dropped_phrases: number,
	/**  鳴らす長さ（ミリ秒）。 */
	duration_ms: number,
	/**
	 *  音の高さの区画が切り替わった位置（`TR-SYN-16`）。
	 * 
	 *  原音設定側の確認対象になる箇所。 単音階では常に空。
	 */
	subbank_switches: SubbankSwitchView[],
};

/**  一覧に出すテイク1件。 */
export type TakeSummaryView = {
	take_id: number,
	/**  何本目か（1 始まり）。 */
	generation: number,
	/**  波形のピーク（0.0〜1.0）。解析がまだなら `null`。 */
	peak: Finite | null,
	duration_ms: number,
	/**  取りこぼしで自動的に無効にした（`TR-REC-07`）。 */
	invalid: boolean,
	/**
	 *  録った時刻（RFC 3339、`DEC-RCL-015`）。
	 * 
	 *  **事実だけ。** 何回に跨るか・何日空いたかは集計しない——
	 *  それは声質の推測材料になる。どう読むかは本人が決める。
	 */
	recorded_at: string,
};

/**  画面へ返すテイク。 */
export type TakeView = {
	/**  台帳の ID。 */
	take_id: number,
	row_id: string,
	duration_ms: number,
	/**  絶対値の最大。`koeru_core::analysis::CLIP_THRESHOLD` 以上ならクリップ。 */
	peak: number,
	/**  波形サムネイル（0〜255）。 */
	thumbnail: number[],
	/**  原音設定が導けたか。 */
	has_oto: boolean,
	/**  境界の確信度。 */
	confidence: number | null,
	/**  取りこぼしの回数（`TR-REC-07`）。 */
	discontinuities: number,
	/**  取りこぼしたので自動的に無効にした。 同じフレーズがもう一度出てくる。 */
	invalidated: boolean,
	/**  押した瞬間より前から何ミリ秒ぶん遡れたか（`TR-REC-19`）。 */
	preroll_ms: number,
	/**  サンプルピーク（dBFS）。無音は `null`。 */
	peak_dbfs: number | null,
	/**  発声の前に確保できた無音（ミリ秒、`TR-REC-38`）。 */
	leading_margin_ms: number,
	/**  発声の後に確保できた無音（ミリ秒、`TR-REC-38`）。 */
	trailing_margin_ms: number,
	/**
	 *  前後 300ms の無音マージンを確保できたか（`TR-REC-38`）。
	 *  足りなくてもテイクは有効。 事実を伝えるだけ。
	 */
	has_required_margins: boolean,
	/**  確定のあとで落ちた工程（[`TakeResult::followup`]）。 テイクは保存済み。 */
	followup: AppError | null,
};

/**  選べる音高1つ（`TR-REC-25`）。 */
export type ToneOptionView = {
	midi: number,
	/**  英語音名。画面に出すのはこちらで、MIDI 番号は出さない。 */
	name: string,
};

/**  音高ひとつぶんの消化率（`TR-RCL-26`）。 */
export type ToneProgressView = {
	/**  英語音名（`TR-REC-25`）。内部は MIDI で、画面に出すのはこちら。 */
	tone: string,
	/**  録り終えた行。 */
	done: number,
	/**  その音高の行の総数。 */
	total: number,
};

/**  収録音高の推奨値1件（`TR-RCL-06`）。 */
export type ToneSuggestionView = {
	label: string,
	/**  なぜこれを勧めるか。1行。 */
	why: string,
	/**  音高（MIDI）。名前は画面が `tone_name` で引く。 */
	midi: number[],
};

/**  CP932 で書けない箇所（`TR-PKG-17`）。 */
export type UnencodableView = {
	/**  `voice_name` / `character_field` / `alias` / `readme_section`。 */
	place: string,
	/**  キー名・節の見出し・エイリアス。音源名のときは `None`。 */
	target: string | null,
	/**  書けなかった文字。 */
	chars: string[],
	/**  代替案。無ければ本人が決める。 */
	suggestion: string | null,
	/**  エイリアスのときだけ、その行へ戻れる。 */
	row_id: string | null,
};

/**  画面へ返す音源のいまの姿。 */
export type VoiceStateView = {
	/**  表示名。一覧では manifest から別に読むので、そこでは空文字。 */
	display_name: string,
	/**  作り方。同上。 */
	method: string,
	/**  録音リストの行の数。同上。 */
	rows: number,
	/**  収録済み単位。 */
	covered: number,
	/**  必要な単位。 */
	required: number,
	/**  いま歌える曲の数（`TR-RCL-19`）。 */
	singable_songs: number,
	/**  バンクに入っている曲の数。 */
	songs_in_bank: number,
	/**  内側から順の環。 */
	rings: RingView[],
	/**  声の色。1つも録れていなければ `None`——空いた席に色を付けない。 */
	color: VoiceView | null,
};

/**
 *  声から作った色（`DEC-PLT-027`）。
 * 
 *  彩度と明度をここで確定させない。 暗い面と明るい面で幅が違うので
 *  （明るい面のほうが sRGB に収まる彩度が狭い）、返すのは 0〜1 の位置だけに
 *  して、面ごとの幅への写しは CSS が持つ。
 */
export type VoiceView = {
	/**  色相（度）。 */
	hue: Finite,
	/**  彩度の位置（0〜1）。 */
	chroma: Finite,
	/**  明度の位置（0〜1）。 */
	lightness: Finite,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

